name = "poet"
version = "0.1.4"

[dependencies]
stanza-toml = "tylanphear/stanza-toml|0.3.0"
semver      = "tylanphear/semver|0.1.3"
maybe-utils = "tylanphear/maybe-utils|0.1.1"
term-colors = "tylanphear/term-colors|0.1.0"
