name = "poet"
version = "0.2.0"

[dependencies]
stanza-toml = "tylanphear/stanza-toml|0.3.2"
semver      = "tylanphear/semver|0.1.3"
maybe-utils = "tylanphear/maybe-utils|0.1.2"
term-colors = "tylanphear/term-colors|0.1.0"
