name: CI

on:
  # Triggers on pushes to master
  push:
    branches: [ master ]

  pull_request:

  # Allows running manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install apt-get dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3 git wget curl unzip gcc

      - name: Download Stanza
        run: |
          # Download archive from lbstanza.org and unpack
          STANZA_VERSION= 0_14_33
          wget "http://lbstanza.org/resources/stanza/lstanza_${STANZA_VERSION}.zip" \
            -O stanza.zip
          unzip stanza.zip -d ${{ github.workspace }}/stanza
          rm -rf stanza.zip

          # Create .stanza in the newly-unpacked Stanza dir
          echo "install-dir = \"/${{ github.workspace }}/stanza\"" >> ${{ github.workspace }}/stanza/.stanza
          echo "platform = linux" >> ${{ github.workspace }}/stanza/.stanza
          ls -la ${{ github.workspace }}/stanza

          # Create Stanza env file for next step
          cat > ${{ github.workspace }}/stanza.env <<EOF
export PATH="${{ github.workspace }}/stanza:\$PATH"
export STANZA_CONFIG="${{ github.workspace }}/stanza"
EOF

      - name: Bootstrap and build
        working-directory: ${{ github.workspace }}
        run: |
          cat ${{ github.workspace }}/stanza.env
          source ${{ github.workspace }}/stanza.env
          ci/build.sh
        env:
          CI_PAT: ${{ secrets.CI_PAT }}
