name: CI

on:
  # Triggers on pushes to master
  push:
    branches: [ master ]

  pull_request:

  # Allows running manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install apt-get dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3 git wget curl unzip gcc

      - name: Download Stanza
        run: ci/download-stanza.sh
        working-directory: ${{ github.workspace }}

      - name: Bootstrap and build
        working-directory: ${{ github.workspace }}
        run: |
          cat ${{ github.workspace }}/stanza.env
          source ${{ github.workspace }}/stanza.env
          ci/build.sh
        env:
          CI_PAT: ${{ secrets.CI_PAT }}
